// One-time / re-run-when-assets-change image pipeline.
// Reads the raw renders in src/assets + public, emits AVIF/WebP/JPEG
// responsive sets into public/images, and writes a generated data module
// (src/data/images.generated.ts) with srcsets + inline LQIP blur placeholders.
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "public", "images");
const DATA_OUT = path.join(ROOT, "src", "data", "images.generated.ts");

const WIDTHS = [480, 960, 1440, 1920, 2560];
const AVIF_OPTS = { quality: 55, effort: 4 };
const WEBP_OPTS = { quality: 68 };
const JPG_OPTS = { quality: 74, mozjpeg: true };

// slug -> source file (relative to repo root)
// Raw high-res originals live in assets-src/ — NOT public/ or src/ — so they
// never get bundled or deployed. Only the derivatives below ship.
const SOURCES = {
  hero: "assets-src/hero-bg.jpg",
  "project-master-bedroom": "assets-src/master-bedroom.png",
  "project-modular-kitchen": "assets-src/modular-kitchen.jpg",
  "project-residential-suite": "assets-src/residential-suite-cover.jpg",
  "residential-floorplan": "assets-src/residential-suite/floorplan.png",
  "residential-kitchen": "assets-src/residential-suite/kitchen.jpg",
  "residential-living-a": "assets-src/residential-suite/living-a.png",
  "residential-living-b": "assets-src/residential-suite/living-b.png",
  "residential-living-c": "assets-src/residential-suite/living-c.png",
  "residential-view-a": "assets-src/residential-suite/view-a.png",
  "residential-view-b": "assets-src/residential-suite/view-b.png",
  "residential-detail-a": "assets-src/residential-suite/detail-a.jpeg",
  "residential-detail-b": "assets-src/residential-suite/detail-b.jpeg",
};

async function ensureDir(dir) {
  if (!existsSync(dir)) await mkdir(dir, { recursive: true });
}

async function lqip(input) {
  const buf = await sharp(input)
    .resize(24, null, { withoutEnlargement: true })
    .blur(2)
    .jpeg({ quality: 40 })
    .toBuffer();
  return `data:image/jpeg;base64,${buf.toString("base64")}`;
}

async function processOne(slug, relSrc) {
  const src = path.join(ROOT, relSrc);
  const buf = await readFile(src);
  const meta = await sharp(buf).metadata();
  const widths = WIDTHS.filter((w) => w <= (meta.width ?? 2560));
  if (widths.length === 0 || widths[widths.length - 1] !== Math.min(meta.width ?? 2560, WIDTHS[WIDTHS.length - 1])) {
    // always include the largest sane width so we don't lose top-end quality
    widths.push(Math.min(meta.width ?? 2560, WIDTHS[WIDTHS.length - 1]));
  }

  const entries = { avif: [], webp: [], jpg: [] };

  for (const w of widths) {
    const base = sharp(buf).resize({ width: w, withoutEnlargement: true });
    const avifPath = `images/${slug}-${w}.avif`;
    const webpPath = `images/${slug}-${w}.webp`;
    const jpgPath = `images/${slug}-${w}.jpg`;

    const [avifBuf, webpBuf, jpgBuf] = await Promise.all([
      base.clone().avif(AVIF_OPTS).toBuffer(),
      base.clone().webp(WEBP_OPTS).toBuffer(),
      base.clone().jpeg(JPG_OPTS).toBuffer(),
    ]);

    await Promise.all([
      writeFile(path.join(ROOT, "public", avifPath), avifBuf),
      writeFile(path.join(ROOT, "public", webpPath), webpBuf),
      writeFile(path.join(ROOT, "public", jpgPath), jpgBuf),
    ]);

    entries.avif.push({ width: w, path: `/${avifPath}` });
    entries.webp.push({ width: w, path: `/${webpPath}` });
    entries.jpg.push({ width: w, path: `/${jpgPath}` });
  }

  const placeholder = await lqip(buf);
  const largestJpg = entries.jpg[entries.jpg.length - 1];

  return {
    slug,
    width: meta.width,
    height: meta.height,
    aspectRatio: +((meta.width ?? 1) / (meta.height ?? 1)).toFixed(4),
    lqip: placeholder,
    fallback: largestJpg.path,
    avif: entries.avif,
    webp: entries.webp,
    jpg: entries.jpg,
  };
}

async function main() {
  await ensureDir(OUT_DIR);
  const slugs = Object.entries(SOURCES);
  console.log(`Optimizing ${slugs.length} source images -> ${slugs.length * WIDTHS.length * 3} derivatives...`);

  const results = {};
  let done = 0;
  for (const [slug, relSrc] of slugs) {
    const srcPath = path.join(ROOT, relSrc);
    if (!existsSync(srcPath)) {
      console.warn(`  ! missing source for "${slug}": ${relSrc}`);
      continue;
    }
    results[slug] = await processOne(slug, relSrc);
    done += 1;
    console.log(`  [${done}/${slugs.length}] ${slug}`);
  }

  const banner =
    "// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n" +
    "// Re-run `npm run optimize-images` after replacing any source render.\n\n";

  const type =
    "export interface ResponsiveSource {\n" +
    "  width: number;\n" +
    "  path: string;\n" +
    "}\n\n" +
    "export interface OptimizedImage {\n" +
    "  slug: string;\n" +
    "  width: number;\n" +
    "  height: number;\n" +
    "  aspectRatio: number;\n" +
    "  lqip: string;\n" +
    "  fallback: string;\n" +
    "  avif: ResponsiveSource[];\n" +
    "  webp: ResponsiveSource[];\n" +
    "  jpg: ResponsiveSource[];\n" +
    "}\n\n";

  const body =
    "export const optimizedImages: Record<string, OptimizedImage> = " +
    JSON.stringify(results, null, 2) +
    ";\n";

  await writeFile(DATA_OUT, banner + type + body, "utf8");
  console.log(`\nWrote ${DATA_OUT}`);
  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
