// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Re-run `npm run optimize-images` after replacing any source render.

export interface ResponsiveSource {
  width: number;
  path: string;
}

export interface OptimizedImage {
  slug: string;
  width: number;
  height: number;
  aspectRatio: number;
  lqip: string;
  fallback: string;
  avif: ResponsiveSource[];
  webp: ResponsiveSource[];
  jpg: ResponsiveSource[];
}

export const optimizedImages: Record<string, OptimizedImage> = {
  "hero": {
    "slug": "hero",
    "width": 1920,
    "height": 1080,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFA//EAB0QAAEFAAMBAAAAAAAAAAAAAAABAgMEERIhIjH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwCJdrsSbI/gusJUusbHPmCzmpukqxOWNeWAbyu9dIAH/9k=",
    "fallback": "/images/hero-1920.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/hero-480.avif"
      },
      {
        "width": 960,
        "path": "/images/hero-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/hero-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/hero-1920.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/hero-480.webp"
      },
      {
        "width": 960,
        "path": "/images/hero-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/hero-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/hero-1920.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/hero-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/hero-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/hero-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/hero-1920.jpg"
      }
    ]
  },
  "project-master-bedroom": {
    "slug": "project-master-bedroom",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAQBAwX/xAAcEAACAwADAQAAAAAAAAAAAAAAAQIDEQQSMkH/xAAXAQADAQAAAAAAAAAAAAAAAAAAAQID/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ALKr9eaNQtSW6Z0a2/pKpnvszqzN3KVj66AmuK4ycu2gMP/Z",
    "fallback": "/images/project-master-bedroom-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/project-master-bedroom-480.avif"
      },
      {
        "width": 960,
        "path": "/images/project-master-bedroom-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/project-master-bedroom-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/project-master-bedroom-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/project-master-bedroom-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/project-master-bedroom-480.webp"
      },
      {
        "width": 960,
        "path": "/images/project-master-bedroom-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/project-master-bedroom-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/project-master-bedroom-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/project-master-bedroom-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/project-master-bedroom-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/project-master-bedroom-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/project-master-bedroom-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/project-master-bedroom-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/project-master-bedroom-2560.jpg"
      }
    ]
  },
  "project-modular-kitchen": {
    "slug": "project-modular-kitchen",
    "width": 1600,
    "height": 900,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAANABgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAE/8QAHRAAAgMAAgMAAAAAAAAAAAAAAAECAxEEEhMUIf/EABYBAQEBAAAAAAAAAAAAAAAAAAMAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwDdTPKdbClf1TYFUnOtJj+JYGSB91P4yMnIgo2vCNT/2Q==",
    "fallback": "/images/project-modular-kitchen-1600.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/project-modular-kitchen-480.avif"
      },
      {
        "width": 960,
        "path": "/images/project-modular-kitchen-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/project-modular-kitchen-1440.avif"
      },
      {
        "width": 1600,
        "path": "/images/project-modular-kitchen-1600.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/project-modular-kitchen-480.webp"
      },
      {
        "width": 960,
        "path": "/images/project-modular-kitchen-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/project-modular-kitchen-1440.webp"
      },
      {
        "width": 1600,
        "path": "/images/project-modular-kitchen-1600.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/project-modular-kitchen-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/project-modular-kitchen-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/project-modular-kitchen-1440.jpg"
      },
      {
        "width": 1600,
        "path": "/images/project-modular-kitchen-1600.jpg"
      }
    ]
  },
  "project-residential-suite": {
    "slug": "project-residential-suite",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAIBBAUG/8QAHBAAAgIDAQEAAAAAAAAAAAAAAQIAAwQREiEi/8QAFgEBAQEAAAAAAAAAAAAAAAAAAgAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AYWqp8MhMlWu0TMi5n6J6i0q9jD61Abqq+LAPYSjioyINtuExP//Z",
    "fallback": "/images/project-residential-suite-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/project-residential-suite-480.avif"
      },
      {
        "width": 960,
        "path": "/images/project-residential-suite-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/project-residential-suite-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/project-residential-suite-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/project-residential-suite-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/project-residential-suite-480.webp"
      },
      {
        "width": 960,
        "path": "/images/project-residential-suite-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/project-residential-suite-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/project-residential-suite-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/project-residential-suite-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/project-residential-suite-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/project-residential-suite-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/project-residential-suite-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/project-residential-suite-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/project-residential-suite-2560.jpg"
      }
    ]
  },
  "residential-floorplan": {
    "slug": "residential-floorplan",
    "width": 2495,
    "height": 1910,
    "aspectRatio": 1.3063,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAASABgDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAMEAQL/xAAfEAACAQQCAwAAAAAAAAAAAAAAAQIDBBEhEjEFMlH/xAAVAQEBAAAAAAAAAAAAAAAAAAABA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ALznLOibnP6cnPjLZCpUk3mPRNRst+UnsHixq83h9gQheGRN4ewALX4z3YAEP//Z",
    "fallback": "/images/residential-floorplan-2495.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-floorplan-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-floorplan-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-floorplan-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/residential-floorplan-1920.avif"
      },
      {
        "width": 2495,
        "path": "/images/residential-floorplan-2495.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-floorplan-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-floorplan-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-floorplan-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/residential-floorplan-1920.webp"
      },
      {
        "width": 2495,
        "path": "/images/residential-floorplan-2495.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-floorplan-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-floorplan-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-floorplan-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/residential-floorplan-1920.jpg"
      },
      {
        "width": 2495,
        "path": "/images/residential-floorplan-2495.jpg"
      }
    ]
  },
  "residential-kitchen": {
    "slug": "residential-kitchen",
    "width": 4000,
    "height": 1919,
    "aspectRatio": 2.0844,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgP/xAAfEAABBAICAwAAAAAAAAAAAAABAAIDEgQREyExMkH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AzjSNBq76qLY4tbqFE8PCd5X09ipulxy6iYhvSEtI4um7O0Jgf//Z",
    "fallback": "/images/residential-kitchen-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-kitchen-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-kitchen-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-kitchen-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/residential-kitchen-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/residential-kitchen-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-kitchen-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-kitchen-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-kitchen-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/residential-kitchen-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/residential-kitchen-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-kitchen-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-kitchen-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-kitchen-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/residential-kitchen-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/residential-kitchen-2560.jpg"
      }
    ]
  },
  "residential-living-a": {
    "slug": "residential-living-a",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEAv/EAB4QAAICAgIDAAAAAAAAAAAAAAECABEDBBITISJB/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AvxN6WsW2xbcDINbaYCvkccvJrrzM1tMgLGEV2EtCB//Z",
    "fallback": "/images/residential-living-a-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-living-a-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-living-a-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-a-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-a-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-a-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-living-a-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-living-a-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-a-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-a-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-a-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-living-a-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-living-a-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-a-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-a-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-a-2560.jpg"
      }
    ]
  },
  "residential-living-b": {
    "slug": "residential-living-b",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFA//EABwQAAICAgMAAAAAAAAAAAAAAAECAAMEERIhQf/EABYBAQEBAAAAAAAAAAAAAAAAAAIAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAh/9oADAMBAAIRAxEAPwApPADUbqcexKluSzK+1k7BgNVdlKn2Em4uSzHTdwmVP//Z",
    "fallback": "/images/residential-living-b-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-living-b-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-living-b-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-b-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-b-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-b-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-living-b-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-living-b-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-b-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-b-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-b-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-living-b-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-living-b-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-b-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-b-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-b-2560.jpg"
      }
    ]
  },
  "residential-living-c": {
    "slug": "residential-living-c",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAIBBAUG/8QAHBAAAgIDAQEAAAAAAAAAAAAAAQIAAwQREiEi/8QAFgEBAQEAAAAAAAAAAAAAAAAAAgAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AYWqp8MhMlWu0TMi5n6J6i0q9jD61Abqq+LAPYSjioyINtuExP//Z",
    "fallback": "/images/residential-living-c-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-living-c-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-living-c-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-c-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-c-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-c-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-living-c-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-living-c-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-c-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-c-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-c-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-living-c-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-living-c-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-living-c-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/residential-living-c-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/residential-living-c-2560.jpg"
      }
    ]
  },
  "residential-view-a": {
    "slug": "residential-view-a",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIEA//EAB0QAAIDAAIDAAAAAAAAAAAAAAABAgMRBBITITL/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwC2+GWahe+L3I3sq8j3SO3hycvshoLYqcW2wGdDhXnbQA//2Q==",
    "fallback": "/images/residential-view-a-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-view-a-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-view-a-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-view-a-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/residential-view-a-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/residential-view-a-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-view-a-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-view-a-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-view-a-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/residential-view-a-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/residential-view-a-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-view-a-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-view-a-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-view-a-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/residential-view-a-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/residential-view-a-2560.jpg"
      }
    ]
  },
  "residential-view-b": {
    "slug": "residential-view-b",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMA/8QAHRAAAgMAAgMAAAAAAAAAAAAAAQIAAxEEEhMiUf/EABYBAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwBcgl7uoOS9fFAG7smKfI/fclFrdSfeSN0ayptK/JoFoK2lu00Qf//Z",
    "fallback": "/images/residential-view-b-2560.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-view-b-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-view-b-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-view-b-1440.avif"
      },
      {
        "width": 1920,
        "path": "/images/residential-view-b-1920.avif"
      },
      {
        "width": 2560,
        "path": "/images/residential-view-b-2560.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-view-b-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-view-b-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-view-b-1440.webp"
      },
      {
        "width": 1920,
        "path": "/images/residential-view-b-1920.webp"
      },
      {
        "width": 2560,
        "path": "/images/residential-view-b-2560.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-view-b-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-view-b-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-view-b-1440.jpg"
      },
      {
        "width": 1920,
        "path": "/images/residential-view-b-1920.jpg"
      },
      {
        "width": 2560,
        "path": "/images/residential-view-b-2560.jpg"
      }
    ]
  },
  "residential-detail-a": {
    "slug": "residential-detail-a",
    "width": 1600,
    "height": 812,
    "aspectRatio": 1.9704,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgP/xAAdEAACAQUBAQAAAAAAAAAAAAAAAQIDBBESIRMi/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDhSjtNIpOxj57R6xehTj57Y6OWk31N5IJ9xxasDd+vtgFf/9k=",
    "fallback": "/images/residential-detail-a-1600.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-detail-a-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-detail-a-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-detail-a-1440.avif"
      },
      {
        "width": 1600,
        "path": "/images/residential-detail-a-1600.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-detail-a-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-detail-a-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-detail-a-1440.webp"
      },
      {
        "width": 1600,
        "path": "/images/residential-detail-a-1600.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-detail-a-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-detail-a-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-detail-a-1440.jpg"
      },
      {
        "width": 1600,
        "path": "/images/residential-detail-a-1600.jpg"
      }
    ]
  },
  "residential-detail-b": {
    "slug": "residential-detail-b",
    "width": 1600,
    "height": 812,
    "aspectRatio": 1.9704,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAD/8QAHhAAAQQCAwEAAAAAAAAAAAAAAQACAwQRIQUSIjH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AEUazZpD3TpOPhaM6Rq/l2lvK4kfSghXK8bWZapblgcMHalB/9k=",
    "fallback": "/images/residential-detail-b-1600.jpg",
    "avif": [
      {
        "width": 480,
        "path": "/images/residential-detail-b-480.avif"
      },
      {
        "width": 960,
        "path": "/images/residential-detail-b-960.avif"
      },
      {
        "width": 1440,
        "path": "/images/residential-detail-b-1440.avif"
      },
      {
        "width": 1600,
        "path": "/images/residential-detail-b-1600.avif"
      }
    ],
    "webp": [
      {
        "width": 480,
        "path": "/images/residential-detail-b-480.webp"
      },
      {
        "width": 960,
        "path": "/images/residential-detail-b-960.webp"
      },
      {
        "width": 1440,
        "path": "/images/residential-detail-b-1440.webp"
      },
      {
        "width": 1600,
        "path": "/images/residential-detail-b-1600.webp"
      }
    ],
    "jpg": [
      {
        "width": 480,
        "path": "/images/residential-detail-b-480.jpg"
      },
      {
        "width": 960,
        "path": "/images/residential-detail-b-960.jpg"
      },
      {
        "width": 1440,
        "path": "/images/residential-detail-b-1440.jpg"
      },
      {
        "width": 1600,
        "path": "/images/residential-detail-b-1600.jpg"
      }
    ]
  }
};
